### PR TITLE
Feature - skill type UI

### PR DESCRIPTION
**Pull request by henrieglesorotos**
**What**

Provides UI for top level concepts for skill type enumerates

**How**

Update config

### CODE REVIEW

**Comment by henrieglesorotos** [comment]
Can I get some 👁️ here pls @namedgraph?

**Comment by namedgraph** [comment]
Skill type is not a `skos:ConceptScheme` but a `skos:Collection` though?

https://github.com/BeameryEdge/bkg-streaming/blob/master/mappings/rchilli/Skill.yml

**Comment by namedgraph** [comment]
https://www.w3.org/TR/skos-reference/#collections

**Comment by henrieglesorotos** [comment]
> Skill type is not a `skos:ConceptScheme` but a `skos:Collection` though?
> 
> https://github.com/BeameryEdge/bkg-streaming/blob/master/mappings/rchilli/Skill.yml

We need a mechanism of showing it as a separate collection of terms from the homepage. That's quite important from a product perspective. We might have to change that mapping to it's a separate vocab, and use `skos:related` to link to skills themselves.

**Comment by namedgraph** [comment]
It should be possible to display Groups as a top-level tab in Skosmos
image

**Comment by henrieglesorotos** [comment]
> It should be possible to display "Groups" (instances of `skos:Collection`) as a top-level tab in Skosmos image

oooohhhhhhh groups. Lemme look.

**Review by namedgraph — COMMENTED** [review]
What about `skosmos:language` for `:roles`?

**Comment by henrieglesorotos** [comment]
> What about `skosmos:language` for `:roles`?

Was going to open another PR for that.

**Comment by namedgraph** [comment]
You're touching that file anyway :)

**Review by namedgraph — APPROVED** [review]

**Pull request merged**
